name: rootify
description: "an Root All In One application for Tweaking, Tuning Performance, AI Management on Your Device, Monitor System Resources, and More"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Design System
  cupertino_icons: 1.0.8
  lucide_icons: 0.257.0
  google_fonts: ^8.0.0
  shimmer: 3.0.0
  flutter_animate: 4.5.2
  dynamic_color: ^1.8.1
  flutter_svg: ^2.0.16
  url_launcher: ^6.3.2
  image_picker: ^1.1.2

  # State Management
  riverpod: ^3.1.0
  flutter_riverpod: ^3.1.0
  riverpod_annotation: 4.0.0
  state_notifier: 1.0.0

  # Root Shell Execution
  root_plus: 1.1.0
  process_run: 1.2.4

  # Service Locators
  get_it: 9.2.0

  # Utilities
  intl: 0.20.2
  uuid: 4.5.2
  device_info_plus: ^12.3.0
  system_info_plus: ^0.0.6
  shared_preferences: ^2.5.4
  flutter_overlay_window: ^0.5.0
  package_info_plus: ^8.1.2
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.12.0
  path: ^1.9.0
  flutter_displaymode: ^0.7.0
  flutter_dotenv: ^5.2.1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 6.0.0
  riverpod_generator: ^4.0.0+1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/bin/
    - lib/shell/sh/
    - assets/credits.json
    - assets/png/
    - assets/svg/
    - assets/license/
    - assets/banner/
    - config.env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#4A90E2"
  adaptive_icon_foreground: "assets/icon/icon.png"
